Warn if twine not present

diff --git a/scripts/publish b/scripts/publish
--- a/scripts/publish
+++ b/scripts/publish
@@ -7,6 +7,11 @@ fi
 
 export VERSION=`${PREFIX}python setup.py --version`
 
+if ! command -v "${PREFIX}twine" &>/dev/null ; then
+    echo "Unable to find the 'twine' command."
+    echo "Install from PyPI, using '${PREFIX}pip install twine'."
+    exit 1
+fi
 
 find taggy -type f -name "*.py[co]" -delete
 find taggy -type d -name __pycache__ -delete
